[default]
src = 'src'
out = 'out'
libs = ['lib']
libraries = []
cache = true
force = false
evm_version = 'london'
## Sets the concrete solc version to use, this overrides the `auto_detect_solc` value
solc_version = '0.8.13'
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
verbosity = 0
ignored_error_codes = []
fuzz_runs = 500
ffi = false
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 0
chain_id = 1
gas_limit = 9_223_372_036_854_775_807
gas_price = 0
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 0
block_difficulty = 0

# See more config options https://github.com/gakonst/foundry/tree/master/config